import { copyFile, mkdir, readdir, unlink, writeFile } from "node:fs/promises";
import { join } from "node:path";

export interface GalleryPage {
    page: string;
    referenceName: string;
    actualName: string;
}

const PAGE_TITLES = [
    "Overview: text, image, and shape positioning",
    "Mapped defaults and text inset",
    "Shared normalization primitives",
    "Paragraph structure",
    "Mixed run typography and links",
    "Bullets and numbering",
    "Text-box fills, borders, and effects",
    "Rotation, direction, and RTL",
    "Wrapping, clipping, and shrink-to-fit",
    "Image sizing and cropping",
    "Image transforms and effects",
    "Core SVG shape geometry",
    "Polygon and star presets",
    "Directional and compound arrows",
    "Arrow callout presets",
    "Bent and routing arrows",
    "Curved and swoosh arrows",
    "Curved-arrow aspect ratios",
    "Circular shape presets",
    "Adjusted arcs and thickness",
    "Flowchart presets 1",
    "Flowchart presets 2",
    "Flowchart presets 3",
    "Brace and bracket presets",
    "Brace and bracket aspect ratios",
    "Ribbon and scroll presets",
    "Ribbon and scroll aspect ratios 1",
    "Ribbon and scroll aspect ratios 2",
    "Action button presets 1",
    "Action button presets 2",
    "Action button aspect ratios",
    "Common symbol presets 1",
    "Common symbol presets 2",
    "Common symbol aspect ratios 1",
    "Common symbol aspect ratios 2",
    "Remaining shape presets 1",
    "Remaining shape presets 2",
    "Remaining shape presets 3",
    "Remaining shape presets 4",
    "Remaining shape presets 5",
    "Remaining shape presets 6",
    "Remaining shape presets 7",
    "Remaining preset aspect ratios 1",
    "Remaining preset aspect ratios 2",
    "Remaining preset aspect ratios 3",
    "Static table sizing, spans, and borders",
    "Table inheritance and cell text options",
    "Automatic table pagination: first page",
    "Automatic table pagination: continuation 1",
    "Automatic table pagination: continuation 2",
    "HTML table import: first page",
    "HTML table import: continuation",
    "Text in arbitrary preset shapes",
] as const;

function image(page: string, kind: "reference" | "actual" | "diff", description: string): string {
    return `<img src="assets/${page}-${kind}.png" width="260" alt="Page ${page} ${description}">`;
}

function galleryMarkdown(pages: GalleryPage[], scores: number[], threshold: number): string {
    if (pages.length !== PAGE_TITLES.length || scores.length !== pages.length) {
        throw new Error(`Gallery metadata mismatch: titles=${PAGE_TITLES.length}, pages=${pages.length}, scores=${scores.length}`);
    }
    const rows = pages.map((page, index) => {
        const title = PAGE_TITLES[index]!;
        return `| **${page.page} — ${title}** (\`${scores[index]!.toFixed(4)}\`) | ${image(page.page, "reference", "reference")} | ${image(page.page, "actual", "PuppeteerGen output")} | ${image(page.page, "diff", "visual difference")} |`;
    }).join("\n");
    return `<!-- Generated by: bun run test:visual:gallery -->
# Visual parity gallery

This gallery compares the same fixture rendered by the pinned PptxGenJS version
and by PuppeteerGen. The PptxGenJS presentation is converted to PDF with
LibreOffice; both PDFs are rasterized at 96 DPI before comparison.

- **Reference:** PptxGenJS → PPTX → LibreOffice PDF
- **Actual:** PuppeteerGen → Puppeteer PDF
- **Diff:** ImageMagick comparison; red edges show differing pixels
- **Score:** whole-slide normalized RMSE; the acceptance limit is \`${threshold.toFixed(2)}\`

The visual test is the source of truth. Regenerate this folder after intentional
rendering changes with:

\`\`\`bash
bun run test:visual:gallery
\`\`\`

The command publishes only the 53 full-page comparison triplets. Feature-level
crops remain transient test artifacts.

| Page, feature, and RMSE | Reference | PuppeteerGen | Diff |
| --- | --- | --- | --- |
${rows}
`;
}

export async function writeVisualGallery(
    artifacts: string,
    pages: GalleryPage[],
    scores: number[],
    threshold: number,
    outputDirectory: string,
): Promise<void> {
    const assets = join(outputDirectory, "assets");
    await mkdir(assets, { recursive: true });
    const generatedName = /^\d+-(?:reference|actual|diff)\.png$/;
    await Promise.all((await readdir(assets))
        .filter(name => generatedName.test(name))
        .map(name => unlink(join(assets, name))));
    await Promise.all(pages.flatMap(page => [
        copyFile(join(artifacts, page.referenceName), join(assets, page.referenceName)),
        copyFile(join(artifacts, page.actualName), join(assets, page.actualName)),
        copyFile(join(artifacts, `${page.page}-diff.png`), join(assets, `${page.page}-diff.png`)),
    ]));
    await writeFile(join(outputDirectory, "README.md"), galleryMarkdown(pages, scores, threshold));
}
